import { Context } from '../../../src/common';
import { pass, fail } from '../../test-utils';
import * as t from 'node:assert/strict';
import { describe, it } from 'vitest';
import { parseSource } from '../../../src/parser';

describe('Expressions - Array', () => {
  for (const arg of [
    '[1 <= 0]',
    '[a, ...b=c]',
    '[a, ...b=c]',
    '[a, ...b=c]',
    '[a, ...(b=c)]',
    '[a, ...b=c.d = 2]',
    '[a, ...b=c]',
    '([a, ...b=c])',
    '[a] = x',
    '[[a] = x]',
    '[[a] = x]',
    '[[a] = [[a] = x]]',
    '[[a] = [[a] = [[a] = [[a] = x]]]]',
    '[a = b] = x',
    '[[a] = b] = x',
    '[,,,] = x',
    '[...a] = x',
    '[...async] = x',
    'v = [...a, b]',
    '[a,] = x',
    '0, [{ x }] = [null]',
    '[a, b] = f();',
    '[...a.b] = x',
    '[[a]] = x',
    '[{x = y}] = z',
    '[...[a]] = x',
    '[(x)] = 1',
    '[,,1,,,2,3,,]',
    '[ 1, 2,, 3, ]',
    '[ 0 ]',
    '[ ,, 0 ]',
    '[,,3,,,]',
    '[x()]',
    '[...a]',
    '[a, ...b]',
    '[...a,]',
    '[, ...a]',
    '[x().foo] = x',
    '[(x().foo)] = x',
    '[...a, ...b]',
    '[...a, , ...b]',
    `[...x, y];`,
    `async(...x/y);`,
    'var array = [,,,,,];',
    'var a = [,];',
    'let a = [];',
    'let b = [42];',
    'let c = [42, 7];',
    'let [d, ...e] = [1, 2, 3, 4, 5];',
    'let [async, ...e] = [1, 2, 3, 4, 5];',
    'let [d, ...async] = [1, 2, 3, 4, 5];',
    'let [async, ...await] = [1, 2, 3, 4, 5];',
    `[...x];`,
    `[...x] = y;`,
    `[...[x].foo] = x`,
    `[...[x]/y]`,
    `(...[x]) => x`,
    `(...{x}) => x`,
    `[...{x}]`,
    `[...{x}] = y`,
    `([...{x}]) => x`,
    `[...{x}/y]`,
    `[...{x} ? y : z]`,
    `[...{x}.foo] = x`,
    `([...[x]]) => x`,
    `[...[x]] = y`,
    `[...[x]]`,
    '[...[...a]]',
    '[a, ...b]',
    '[function* f() {}]',
    '[a, ...{0: b}] = (1);',
    '[...{a}] = b;',
    '[...{a}] = b;',
    '[a, ...{0: b}] = 1',
    '[1, "z", "a", "Symbol(foo)"]',
    '[1, 2, 3, ...[]]',
    ' [...{}];',
    '[1,2,,4,5];',
    `[a,]`,
    `[a,,]`,
    `[a,a,]`,
    `[a,,,]`,
    '([...x]) => y',
    '([...async]) => y',
    '[...(x,y)]',
    '[...(x,y)]',
    `[a,a,,]`,
    `[,a]`,
    `[,a,]`,
    `[,a,,]`,
    `[,a,a,]`,
    `[,a,]`,
    `[,a,,]`,
    `[,a,a,]`,
    `[,,a]`,
    `[,a,a]`,
    `[,,a,]`,
    `[,,a,]`,
    `[,,,a]`,
    `[,,a,a]`,
    'a = [,]',
    'a = [,]',
    '[[1,2], [3], []]',
    '[1,2,,4,5]',
    '[0, ...a];',
    '[...iter];',
    'a = [,] = b = [] = c[9]',
    'a = [(b), (c), (d)]',
    'a = [(b) => {}, (c) => {}, (d) => { [b]}]',
    'a = [(b) => {}, [(b) => {}, (c) => {}, (d) => { [b]}]]',
    'a = [,]',
    'a = [,]',
    'a = [a = [,],a = [a = [,],a = [,]]]',
    'async = [,]',
    `async ([[[]]]) => [[,,a,a=> {}]]`,
    `[[,,a,a=> {}]]`,
    `[[,,a=> {},a]]`,
    `[[a=> {},,a,]]`,
    `[[] = [9], {} = [], c = d, [,,a,a=> {}]]`,
    `[[,,a,a=> {}]]`,
    '([].x);',
    '[...this, y];',
    '[...x, y];',
    '[...x];',
    '[...x] = y;',
    '[...async] = y;',
    '[...this];',
    '[...new x];',
    '[...x/y];',
    '[...x = x];',
    '([...x=y])',
    'async([].x);',
    '[...[a]=1]',
    '[...[1]]',
    '[...[1], ..."foo" ]',
    '[...[1], ...2 ]',
    '[...[1], ..."foo", ]',
    '[...[1], ...2 ,]',
    '[...[1], ..."a".b]',
    '[...[1], ..."a"[b]]',
    '[...[1], ..."a"(b)]',
    '[...[1], ["a"](b)]',
    '[...[1], "a"(b)]',
    '[...a]',
    '[a, ...b]',
    '[...a,]',
    '[...a, ,]',
    '[, ...a]',
    '[...a, ...b]',
    '[...a, , ...b]',
    '[...[...a]]',
    '[...[...async]]',
    '[, ...a]',
    '[, , ...a]',
    '[,]',
    `[...50..bar]`,
    `[...50]`,
    '[...a=b]',
    '[{}.foo] = x',
    '[{}[foo]] = x',
    `[[]]`,
    '([...x]) => x',
    '([...x]);',
    '([...x=y]);',
    '([...x, ...y]);',
    '([...x.y] = z)',
    '([...x, ...y]);',
    '[{}.foo]=x',
    '[5[foo]]=x',
    '["x".foo]=x',
    '[`x`.foo]=x',
    `[x]=y`,
    `[x=y]=z`,
    `({"a b c": bar});`,
    `({"a b c"(){}});`,
    `({"a b c": bar}) => x`,
    `({15: bar});`,
    `({15(){}});`,
    `({15: bar}) => x`,
    `({25: true})`,
    `({"x": true})`,
    '[a.b=[c.d]=e] = f;',
    '([a=[b.c]=d]) => e;',
    '[{x: y.z}]',
    '[{x: y.z}] = a',
    '([a] = b) => c;',
    '([a]) => b;',
    'const [a] = b;',
    'function foo([a]){};',
    'function foo([a] = b){};',
    '({"foo": [x].foo}=y);',
    '[...foo] = bar',
    `for ([...a.b] in c) d`,
    `[...a.b]=c`,
    '[...a.b]=c',
    '[...a.b] = c',
    '([...a.b] = c)',
    '([...[x]]) => x',
    '[(a)] = x',
    '(z = [...x.y] = z) => z',
    '(z = [...x.y]) => z',
    '[...[x]=y];',
    '[...[{a: b}.c]] = [];',
    '[...[{prop: 1}.prop]] = []',
    '({ a: {prop: 1}.prop } = {})',
    '[{a: 1}.c] = [];',
    '[({a: 1}.c)] = [];',
    '[[1].c] = [];',
    '[foo.foo, foo.bar] = [1, 2];',
    '[([1].c)] = [];',
    '({ a: {prop: 1}.prop } = {})',
    'var [, a, , b] = x',
    'var [] = x',
    'var [...a] = x;',
    'var [a] = x;',
    '[foo, bar] = [0,1];',
    '[a,a,,...a]=0',
    '[,,]=0',
    '[...a[0]] = 0',
    '[...{ a }] = b',
    '[[[[[[[[[[[[[[[[[[[[{a=b[0]}]]]]]]]]]]]]]]]]]]]]=0;',
    '[(a) = 0] = 1',
    '[(a.b)] = 0',
    '[a = (b = c)] = 0',
    '[(a = 0)]',
    '({a:(b)} = 0)',
    '({a:(b) = 0} = 1)',
    '({a:(b.c)} = 0)',
    '({a:(b = 0)})',
    '[a] = 0;',
    `[...a = b] `,
    'result = [ x = yield ] = [[22]];',
    'result = [[x[yield]]] = [[22]];',
    '[{...o, ...o2}]',
    '([...x=y])',
    '[...this, y];',
    '({...this, y})',
    '[1, "z", "a", "Symbol(foo)"]',
    '(null, [...[]])',
    'apply(null, [...[]])',
    '[...target = source]',
    '[{a: 1, b: 2, ...null}]',
    '[{a: 1, b: 2, ...o}]',
    '[5, ...[6, 7, 8], 9]',
    '[,,,1,2]',
    '[,,,,,,,,,,,,,,,,,,,,,,,,,]',
    '[,,,,a,,,,,,b,,,,,,,,,1,,,,,,]',
    '[,,,,,,,,[5, ...[6, 7, 8], 9],,,,,,,,,,,,,,,,,]',
    '[,,,,,,,,,,,,,,,,,,,,,,,,,]',
    '[,,,,,,,,,,,,,,,,,,,,,,,,,]',
    '[,,3,,,];',
    '[[1,2], [3], []];',
    '[101];',
    '[...a[0]] = 0;',
    '[a,b=0,[c,...a[0]]={}]=0;',
    'result = [ xFn = function x() {}, fn = function() {} ] = vals;',
    '[ arrow = () => {} ]',
    '[ xCls = class x {}, cls = class {}, xCls2 = class { static name() {} } ]',
    '[ xCover = (0, function() {}), cover = (function() {}) ]',
    'result = [ x = "x" in {} ] = vals;;',
    '0, [ x = y ] = [];',
    '[ a = x += 1, b = x *= 2 ]',
    '[arguments = 4, eval = 5]',
    '[ x = yield ] ',
    '0, [[ _ ]] = [null];',
    '[[1]];',
    '0, [ x ] = [];',
    '[ x[yield] ] = [33];',
    '[,] = [];',
    '["x".foo] = x',
    '[5[foo]] = x',
    '[,] = [];',
    '[] = null',
    '[] = true',
    '[, , x, , ...y] = [1, 2, 3, 4, 5, 6];',
    '[...[x]]  = [ , ];',
    '[...[x[yield]]] =[101];',
    '[...[async[yield]]] = [await];',
    '[...x[yield]] =[101];',
    '0, { yield } = {};',
    '[[[[[[[101]]]]]]];',
    '[[[[[[[a]]]]]]] = b;',
    '[[[[[[[a=b]]]] = c] = c] = c] = c;',
    '[[[[[[[a=b] = c] = c] = c] = c] = c] = c] = c;',
    '[[[[[[[a=b]] = c]] = c] = c] = c] = c;',
    '[[[[[[[a=b] = c]]] = c] = c] = c] = c;',
    '[[[[[[[a=b]]]] = c] = c] = c] = c;',
    '[[[[[[[a=b] = c] = c] = c] = c] = c] = c] = [[[[[[[a=b] = c]]] = c] = c] = c] = c;',
    '[[[[[[[a=b]] = c]] = c] = c[[[[[[[a=b] = c]]] = c] = c] = c] = c] = c] = c;',
    '[1, ...rest]',
    '[...rest, 1]',
    '[...rest, ,1]',
    '[{a: 0}.x] = [];',
    '[[0].x] = [];',
    '[...{a: 0}.x] = [];',
    '[...[0].x] = [];',
    '({a: {b: 0}.x} = {});',
    '({a: [0].x} = {});',
    '({...{b: 0}.x} = {});',
    '({...[0].x} = {});',
    '({...{eval}.x} = {});',
    '[{eval}.x] = [];',
    '[...{eval}.x] = [];',
    '[...{eval}.x] = [[...{arguments}.x] = []];',
    '({a: {eval}.x} = {});',
    '[...{arguments}.x] = [];',
    '[a]',
    '[[a] ? x : bcd]',
    '[[a] / bcd]',
    '([a] / bcd)',
    '[({a})]',
    '[({a}), ({b})]',
    '[(({a}), ({b}))]',
    '([(({a}), ({b}))])',
    '[a]',
    '[a]',
    '[a]',
    '[a, b] = [10, 20];',
    '[a, b.c.d = (a) / 2 ] = [10, 20];',
    '({a, b, ...rest} = {a: 10, b: 20, c: 30, d: 40});',
    '[a=5, b=7] = [1];',
    '[a=5, b=(7)] = ([1]);',
    '[a=5, b=(async)] = ([1]);',
    '[a=5, b=("foo")] = ([async]);',
    '[a=5, b=(7).c.d] = ([1]);',
    '[a, b] = [b, a];',
    '[a, b.c] = [d.e, f.g];',
    '[a, b.c] = [d.e, (f.g) = h];',
    '[a, b] = f(() => {  }); ',
    '[a, b] = f(() => { [a, b.c] = [d.e, (f.g) = h]; }); ',
    '([a, b] = f(() => { [a, b.c] = [d.e, (f.g) = h]; }));',
    '[a, b] = f(); ',
    'var [a, , b] = f();',
    '[a, ...b] = [1, 2, 3];',
    '[a, ...b] = [1, 2, ...c];',
    '[a, ...b] = [1, 2, ...(c / 2)];',
    '[a, ...b] = [1, 2, ...c / 2];',
    '[a, ...b] = ([1, 2, ...c / 2]);',
    '[async, ...b] = ([1, 2, ...c / 2]);',
    '[a, ...b] = ([1, 2, ...async / 2]);',
    'o = {p: 42, q: true};',
    'await = {p: 42, q: true};',
    '[o = {p: 42, q: true}];',
    '([o = {p: 42, q: true}]);',
    '[a, b, ...rest] = [10, 20, 30, 40, 50];',
    '[[[a.b =[]]]]',
    '[[[a.b =[{ x: x.b }]]]]',
    '[[[a.b =[{ x: x.b }]]]]',
    '[[[a.b =[{ x: x.b }]]] = abc]',
    '[(a) = (b)]',
    '[(x) = y = (z)]',
    '[(x) = y = (z) => (a)]',
    '[(x) => y = (z)]',
    '[(x), y = x] = x;',
    '[(x), y] = x;',
    '[(async), y] = x;',
    '[(x), async] = x;',
    '[(x), await] = x;',
    '[(x), async] = await;',
    '[(x), y] = x;',
    '[a, b, c];',
    '[x.y = 42]',
    '[{}[x ? y : z] += a]',
    '[ c.d === e ? f : g ]',
    '["b" === e ? f : g ]',
    '[ [b].c.d === e ? f : g ]',
    '[{}[x ? y : z] += a]',
    '[ c.d === (e ? f : g )]',
    '[ c.d === (e ? f : g ) ? x : y]',
    '[["b"] === e ? f : g ]',
    '[([b].c.d) === {string} ? f : g ]',
    '[([3].c.d) === e ? f : g /= 1]',
    '[{}[x ? {zzz} : (z)] /= a]',
    '[ c.d === e ? (f) : (g) ]',
    '["b" === e ? f : g ]',
    '[ [b].c.d === e ? f : g ]',
    '[{}[x ? y : z] += a]',
    '[ c.d === (e ? f : g )]',
    '[ c.d === (e ? f : g ) ? x : y]',
    '[["b"] === e ? f : g ]',
    '[([b].c.d) === e ? f : g ]',
    '[([b].c.d) === e ? f : g /= 1]',
    '[...{}[x ? {zzz} : (z)] /= a]',
    '[ ...c.d === e ? (f) : (g) ]',
    '[..."b" === e ? f : g ]',
    '[...[b].c.d === e ? f : g ]',
    '[...{}[x ? y : z] += a]',
    '[...[][x ? y : z] += a]',
    '[ c.d === (e ? f : g ) ? x : y]',
    '[(x.y) = 42]',
    '[(x.y) = [1/42]]',
    '[(x.y) = [1/42]]',
    '[x.y = 42]',
    '[[], [b, c], []];',
    '[a,, b,];',
    '[a,,,, b];',
    '[a, b,, c];',
    '[(a), ] = x;',
    '([(x), y] = x);',
  ]) {
    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`${arg}`, undefined, Context.None);
      });
    });
    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`${arg}`, undefined, Context.OptionsLexical);
      });
    });

    it(`() => {${arg}}`, () => {
      t.doesNotThrow(() => {
        parseSource(`() => {${arg}}`, undefined, Context.None);
      });
    });

    it(`function foo() { ${arg}}`, () => {
      t.doesNotThrow(() => {
        parseSource(`function foo() { ${arg}}`, undefined, Context.OptionsWebCompat);
      });
    });

    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`${arg}`, undefined, Context.OptionsWebCompat);
      });
    });
  }

  fail('Expressions - Array (fail)', [
    ['[(x.y) = [1/42]/=2]', Context.None],
    ['[[[[[[[[[[[[[[[[[[[[{a=b}]]]]]]]]]]]]]]]]]]]]', Context.None],
    [`[{}[x ? {zzz} : (z)] /= ...a]`, Context.None],
    ['[{} = 2/=2]', Context.None],
    ['["b" /= e ? f : g ]', Context.None],
    ['[([b].c.(d)) **= e ? f : g /= 1]', Context.None],
    ['[([b].c.(d) / x - 2) **= e ? f : g /= 1]', Context.None],
    ['[...[x ? y : z] += a]', Context.None],
    [`try {} catch ([...a.b]) {}`, Context.None],
    [`[ c.d === (...e ? f : g )]`, Context.None],
    [`let [...a.b]=c`, Context.None],
    [`[["b"] /= e ? f : g ]`, Context.None],
    ['[{} /= 2]', Context.None],
    ['[{x=y} = 2/=2]', Context.None],
    ['[ c.d === (...[e] ? f : g )]', Context.None],
    ['[x.[y] = 42]', Context.None],
    [`[x.[y] = [z]]`, Context.None],
    [`for (let [...a.b] in c) d`, Context.None],
    ['[...[1], ...1.a]', Context.None],
    ['let [...a, b] = [];', Context.None],
    ['[...break]', Context.None],
    ['[...break }', Context.None],
    ['[...break :', Context.None],
    ['[...break', Context.None],
    ['[...a, b] = v', Context.None],
    ['[(a), async(await[async])] = x;', Context.None],
    [`[...this] = x;`, Context.None],
    [`[...this] => x;`, Context.None],
    [`[{a: 1} = []];`, Context.None],
    [`[{a: 1} = []];`, Context.None],
    [`[{a: 1} = []];`, Context.None],
    [`[{a: 1} = []];`, Context.None],
    [`[...a, ...b] = x`, Context.None],
    [`[([a])] = x`, Context.None],
    [`[([async])] = x`, Context.None],
    [`[...a,] = x`, Context.None],
    [`[{x = y}]`, Context.None],
    [`({a: {b = 0}.x} = {})`, Context.None],
    [`() => {({a: {b = 0}.x} = {})}`, Context.None],
    [`function foo() { ({a: {b = 0}.x} = {})}`, Context.None],
    [`({a: {b = 0}.x} = {})`, Context.None],
    ['[/[/]', Context.None],
    ['[{a = 0}.x] = [];', Context.None],
    ['() => {[{a = 0}.x] = [];}', Context.None],
    ['[{a = 0}.x] = [];', Context.None],
    ['[...x, ...y] = [];', Context.None],
    ['[...{a = 0}.x] = []', Context.None],
    ['() => {[...{a = 0}.x] = []}', Context.None],
    ['() => {({...{b = 0}.x} = {})}', Context.None],
    ['[...x, ...y] = [];', Context.None],
    ['[...x, ...y] = [];', Context.None],
    // [`++[a];`, Context.None],
    [`[...{0=x} = c] `, Context.None],
    [`[...{a: 0=x} = c] `, Context.None],
    [`[...{0} = c] `, Context.None],
    [`[...{a: 0} = c]`, Context.None],
    [`({x:0 = 5})`, Context.None],
    [`([...x=y]) = z`, Context.None],
    [`([...x=y]) => z`, Context.None],
    [`({*a([a.b]){}})`, Context.None],
    [`try {} catch ({e: x.a}) {}`, Context.None],
    [`var {a: b.c} = 0;`, Context.None],
    [`([a.b]) => 0`, Context.None],
    [`function a([a.b]) {}`, Context.None],
    [`({a([a.b]){}}`, Context.None],
    [`({set a([a.b]){}})`, Context.None],
    [`let [...x=y] = z`, Context.None],
    [`[...{true=x} = c]`, Context.None],
    [`[...{a: true=x} = c]`, Context.None],
    [`([x]=await y)=>z`, Context.None],
    [`[x=y]=await z`, Context.None],
    [`[...{true} = c]`, Context.None],
    [`[...{a: function=x} = c]`, Context.None],
    [`[...{a: true=x} = c]`, Context.None],
    [`({x:true = 5})`, Context.None],
    [`var [a]; `, Context.None],
    [`var ([a]) = x;`, Context.None],
    [`var [...a, b] = x;`, Context.None],
    [`var [...a,] = x;`, Context.None],
    ['[x] += 0', Context.None],
    ['[, x, ...y,] = 0', Context.None],
    ['[...x, ...y] = 0', Context.None],
    ['({[a / b = c]: {}})', Context.None],
    ['[...x, y] = 0', Context.None],
    ['[...x,,] = 0', Context.None],
    ['[0,{a=0}] = 0', Context.None],
    ['[{a=0},{b=0},0] = 0', Context.None],
    ['[{a=0},...0]', Context.None],
    ['[...0,a]=0', Context.None],
    ['[...0,{a=0}]=0', Context.None],
    ['[...0,...{a=0}]=0', Context.None],
    ['function foo() { [a, ...{b=c}]}', Context.None],
    ['() => {[a, ...{b=c}]}', Context.None],
    ['([[a](b.c) = [[a] = [[a] = ([[a] = x]]]]))', Context.None],
    ['([[a](b) = [[a] = [[a] = ([[a] = x]]]]))', Context.None],
    ['[[a] = [[a] = [[a] = ([[a] = x]]]])', Context.None],
    ['([[a] = [[a] = [[a] = ([[a] = x]]]]))', Context.None],
    ['[...a, ,] = [...a, ,]', Context.None],
    ['([...a, ,] = [...a, ,])', Context.None],
    ['[...{a=0},]', Context.None],
    ['[...{a=0},]=0', Context.None],
    ['[0] = 0', Context.None],
    ['[a, ...b, {c=0}]', Context.None],
    ['{a = [...b, c]} = 0', Context.None],
    ['[a, ...(b = c)] = 0', Context.None],
    [`[...await]`, Context.Module],
    [`[...await]`, Context.InAwaitContext],
    [`[...yield]`, Context.Strict],
    [`[.../x//yield]`, Context.Strict],
    ['[...await] = obj', Context.Module],
    ['[...await] = obj', Context.InAwaitContext],
    ['[...yield] = obj', Context.Strict],
    ['async x => [...await x] = obj', Context.None],
    ['[...a + b] = c', Context.None],
    ['function *f(){ return [...yield] = obj; }', Context.None],
    ['function *f(){ return [...yield x] = obj; }', Context.None],
    ['({...yield} = obj)', Context.Strict],
    ['async([].x) => x;', Context.None],
    [`[x=await y]=z`, Context.None],
    [`[x=await y]=z`, Context.None],
    [`[.../x/ y]`, Context.None],
    [`[...{a = b} = c] = x`, Context.None],
    ['([...{a = b} = c]) => d;', Context.None],
    ['[...{a = b} = c] = d;', Context.None],
    ['result = [...{ x = yield }] = y;', Context.Strict],
    ['[true = x] = x', Context.None],
    ['[(...)]', Context.None],
    ['(...)', Context.None],
    ['[...this, y] = foo;', Context.None],
    ['[{..}, x]', Context.None],
    ['[{..}, x]', Context.None],
    ['[{..}]', Context.None],
    ['[{..}.x]', Context.None],
    ['[{..}=x]', Context.None],
    [`[[async].await()] = x`, Context.None],
    [`[[foo].food()] = x`, Context.None],
    [`[[foo].food() = x] = x`, Context.None],
    [`[[..][foo]] = x`, Context.None],
    [`[[..].foo] = x`, Context.None],
    [`[[..]=x]`, Context.None],
    [`[[..].x]`, Context.None],
    [`[[..], x]`, Context.None],
    [`[[..]]`, Context.None],
    [`([...x.y]) => z`, Context.None],
    [`([...x.y] = z) => z`, Context.None],
    ['[a, ...]', Context.None],
    ['[..., ]', Context.None],
    ['[a=5, b=7] = ([1]) = x;', Context.None],
    ['[a=5, b=7] = ([1]) => x;', Context.None],
    ['[a=5, b=7] = ([1]) => x;', Context.None],
    ['[(a=5, b=(x)) = y] = ([1]);', Context.None],
    ['[(a=5, b=(7))] = ([1]);', Context.None],
    ['[a=5, b=(7).c.(d)] = ([1])', Context.None],
    ['[a=5, b=(7).c.(d)[e]] = ([1]);', Context.None],
    ['([a] / ...bcd)', Context.None],
    ['([a], ...[bcd] = (x))', Context.None],
    ['([a], ...bcd = (x))', Context.None],
    ['([(({a.b.c[d]}), ({b = c / 2}))])', Context.None],
    ['([(({a[d]}), ({b = c / 2}))])', Context.None],
    ['([(({a}), ({b = c / 2}))])', Context.None],
    ['[..., ...]', Context.None],
    ['[ (...a)]', Context.None],
    ['[true = x]', Context.None],
    ['[this] = x', Context.None],
    ['[false] = x', Context.None],
    ['[false] = x', Context.None],
    ['[function(){}] = x', Context.None],
    ['[new x] = x', Context.None],
    ['[null] = x', Context.None],
    ['[true] = x', Context.None],
    ['[typeof x] = x', Context.None],
    ['[void x] = x', Context.None],
    ['[--x = 1]', Context.None],
    ['[...x += y] = a;', Context.None],
    ['[await = x] = x', Context.Module],
    ['[...a = 1 = a]', Context.None],
    ['[...1 = a]', Context.None],
    ['[this] = obj', Context.None],
    ['[x, ...y, z] = obj', Context.None],
    ['[x, y, ...z()] = obj', Context.None],
    ['[x, ...z = arr, y] = obj', Context.None],
    ['[x, ...z(), y] = obj', Context.None],
    ['[x, ...z + arr, y] = obj', Context.None],
    ['[...this] = obj', Context.None],
    ['[...true] = x', Context.None],
    ['[...true] => x', Context.None],
    ['[...new] = x', Context.None],
    ['[...new]', Context.None],
    ['[..."foo"=x] = x', Context.None],
    ['[...[a](1)=2] = 3', Context.None],
    ['[...[a](1)] = 3', Context.None],
    ['[...[a].1] = 3', Context.None],
    ['[...[1], "a"(b)] = x', Context.None],
    ['[...[1], ["a"](b)] = x', Context.None],
    ['[...]', Context.None],
    ['[..."x"=b]', Context.None],
    ['[...a=b] = x', Context.None],
    ['[..."foo".foo=x] = x', Context.None],
    ['[x, y, ...z = arr] = obj', Context.None],
    ['[x, y, ...z = arr] = x = obj', Context.None],
    ['[..."foo"+bar] = x', Context.None],
    ['[...[a](1)] = 3', Context.None],
    ['[...[x].map(y, z)] = a;', Context.None],
    ['[ ...([a] = []) = a;', Context.None],
    ['[ x += x ] = a;', Context.None],
    ['[...++x] = a;', Context.None],
    ['[...x--] = a;', Context.None],
    ['[...!x] = a;', Context.None],
    ['[...x + y] = a;', Context.None],
    ['[...z = 1] = a;', Context.None],
    ['[x, y, ...z = 1] = a;', Context.None],
    ['[...x,] = a;', Context.None],
    ['[x, ...y, z] = a;', Context.None],
    ['[async(x,y) => z] = a;', Context.None],
    ['[async x => z] = a;', Context.None],
    ['[--x = 1] = a;', Context.None],
    ['[this=x]', Context.None],
    ['[false=x]', Context.None],
    ['[true=x]', Context.None],
    ['[x()] = a;', Context.None],
    ['[this = 1] = a;', Context.None],
    ['[x--] = a;', Context.None],
    ['[--x = 1] = a;', Context.None],
    ['[[[[[[[a=b] = c]]] = c] = (c=d)] = c] = ({a = b}) = foo;', Context.None],
    ['[async x => z] = a;', Context.None],
    ['[x, y, ...[z] = [1]] = a;', Context.None],
    ['[...[z] = [1]] = a;', Context.None],
    ['[...rest, x] = x', Context.None],
    ['[a,b,...rest, x] = x', Context.None],
    ['[...rest,] = x', Context.None],
    ['[a,b,...rest,...rest1] = x', Context.None],
    ['[a,,..rest,...rest1]  = x ', Context.None],
    ['{...[ x = 5 ] }', Context.None],
    ['{...[x] } = x', Context.None],
    ['{...[ x = 5 ] }', Context.None],
    ['{...[ x = 5 ] }', Context.None],
    ['[x + y] = x', Context.None],
    ['x, [foo + y, bar] = doo', Context.None],
    ['[50] = a;', Context.None],
    ['[0,{a=0}] = 0', Context.None],
    ['[0] = 0', Context.None],
    ['x, [foo + y, bar] = zoo;', Context.None],
    ['[x[yield]]] = value;', Context.None],
    ['[[(x, y)]] = x;', Context.None],
    ['[...[(x, y)]] = x;', Context.None],
    ['[ ...[ ( [ a ] ) ] ] = a;', Context.None],
    ['[(foo())] = a;', Context.None],
    ['[ ([a]) ] = a;', Context.None],
    ['[ (++y) ] = a;', Context.None],
    ['([this]) => x;', Context.None],
    ['[break]', Context.None],
    ['[implements]', Context.Strict | Context.Module],
    ['"use strict"; [implements]', Context.None],
    ['x, [foo + y, bar] = doo;', Context.None],
    ['[...{a: true} = c]', Context.None],
    ['[[[a.b =[{ x: x.b }]]]] = ([{ a = b / 2}])', Context.None],
    ['[[[a.b =[{ x: x.b = 123 }]a(b=c)]]]', Context.None],
    ['[(a.b.c.d = e) = ()]', Context.None],
    ['function foo() { [(a.b.c.d = e) = ()]}', Context.None],
    ['[() = ()]', Context.None],
    ['[(1) = (a = b)]', Context.None],
    ['[(1) = (a = b.c)]', Context.None],
    ['[([{ x = y }] = b.call(c)) = ()]', Context.None],
    ['[(a = b.call(c)) = ()]', Context.None],
    ['[(a = b.call(c)) = (a = b / 2)]', Context.None],
    ['[(a = async.call(c)) = (a = b / 2)]', Context.None],
  ]);

  pass('Expressions - Array (pass)', [
    ['[(x) = y = (z) => (a)]', Context.None],
    ['[.../x//yield]', Context.None],
    ['x, [foo, bar] = doo;', Context.None],
    ['x, [foo = y, bar] = doo', Context.None],
    ['function *f(){ return [...yield x]; }', Context.OptionsRanges],
    ['"use strict"; const { [eval]: []} = a;', Context.OptionsRanges | Context.OptionsRaw],
    ['function *f(){ return [...yield]; }', Context.OptionsRanges],
    ['[x = true] = y', Context.OptionsRanges],

    ['[[x] = true] = y', Context.None],
    ['[[x = true] = true] = y', Context.None],
    ['["foo".foo] = x', Context.None],
    ['result = [...{ x = yield }] = y;', Context.None],
    ['[/foo/.length] = x', Context.None],
    ['function* g() {   [...{ x = yield }] = y   }', Context.None],
    ['[...{x}=y];', Context.None],
    ['[(a)] = 1', Context.None],
    ['[x,] = 0', Context.None],
    ['[[x]] = 0', Context.None],
    ['[...this];', Context.OptionsWebCompat],
    ['[...x.list];', Context.None],
    ['[...x.list] = a;', Context.OptionsRanges],
    ['[, x,,] = 0', Context.OptionsRanges],
    ['[...[x]] = 0', Context.OptionsRanges],
    ['[...{x = 1}] = [{}]', Context.None],
    ['[...[x]] = 0', Context.None],
    ['[x, ...{0: y}] = 0', Context.None],
    ['[x, x] = 0', Context.None],
    ['[(a)] = 0', Context.None],
    ['({x} = 0)', Context.None],
    ['[ x = "x" in {} ] = value;', Context.None],
    ['a = [ a = x += 1, b = x *= 2 ] = value;', Context.None],
    ['[{ x }] = [null];', Context.None],
    ['[{ x }] = [ , ];', Context.None],
    ['a = [{ x = yield }] = value;', Context.None],
    ['a = [[x[yield]]] = 123;', Context.None],
    ['[{ x }] = [];', Context.None],
    ['a = [{ x }] =  [{ x: 2 }];', Context.None],
    ['a = [x.y] = [123];', Context.None],
    ['[x, ...y] = [1, 2, 3];', Context.None],
    ['[, ...x] = [1, 2, 3];', Context.None],
    ['a = [x.y] = value;', Context.None],
    ['a = [ x[yield] ] = [33];', Context.None],
    ['a = [...[x, y]] = [null];', Context.None],
    ['a = [...[x]] = [ , ];', Context.None],
    ['a = [...{ 0: x, length }] = [undefined];', Context.None],
    ['a = [...x.y] = [4, 3, 2];', Context.None],
    ['a = [...[x[yield]]] = [2018];', Context.None],
    ['a = [...{ 0: x, length }] = value;', Context.None],
    ['a = [...{ 1: x }] = [1, 2, 3];', Context.None],
    ['[,] = null;', Context.None],
    ['[[x]] = [[1]];', Context.None],
    ['a = [ x = yield ] = [];', Context.None],
    ['result = [, x, , y, ,] = [1, 2, 3, 4, 5, 6];', Context.None],
    ['a = [ x = flag = true ] = [];', Context.None],
    ['a = [ a = x += 1, b = x *= 2 ] = [];', Context.None],
    ['a = [arguments = 4, eval = 5] = value;', Context.None],
    ['[a,b=0,[c,...a[0]]={}]=0', Context.None],
    ['[a,a,,...a]=0;', Context.None],
    ['[{a=b}=0]', Context.None],
    ['[a = 0, ...{b = 0}] = 0', Context.None],
    ['[{a=0}, ...b] = 0', Context.None],
    ['[x[a]=a] = 0', Context.None],
    ['[x.a=a] = 0', Context.None],
    ['[{a=0},{a=0}] = 0', Context.None],
    ['[...[...a[x]]] = 1', Context.None],
    ['for([a,b[a],{c,d=e,[f]:[g,h().a,(0).k,...i[0]]}] in 0);', Context.None],
    ['[[[[[[[[[[[[[[[[[[[[{a=b[0]}]]]]]]]]]]]]]]]]]]]]=0;', Context.None],
    ['[ { x = 10 } = {} ]', Context.None],
    ['[ { x : foo()[y] = 10 } = {} ]', Context.None],
    ['[ [ foo().x = 10 ] = {} ]', Context.None],
    ['[x, y, ...z = 1]', Context.None],
    ['[...z = 1]', Context.None],
    ['function x([ a, b ]){}', Context.None],
    ['function a([x, , [, z]]) {}', Context.None],
    ['[a,,b] = array;', Context.None],
    ['[x = 10, y, z] = a;', Context.None],
    ['[ok.v] = 20;', Context.None],
    ['([y]) => x;', Context.None],
    ['[{a = 0}] = [{}];', Context.None],
    ['[{a = 0}] = [{}];', Context.None],
    ['function f([...[{a = 0}]]) {}', Context.None],
    ['h = ([...[{a = 0}]]) => {};', Context.None],
    ['function f1({a} = {a:1}, b, [c] = [2]) {}', Context.None],
    ['[arguments] = []', Context.None],
    ['[...{a}] = [{}];', Context.None],
    [
      '[{x : [{y:{z = 1}, z1 = 2}] }, {x2 = 3}, {x3 : {y3:[{z3 = 4}]}} ] = [{x:[{y:{}}]}, {}, {x3:{y3:[{}]}}];',
      Context.None,
    ],
    ['[[ x ]] = [ , ];', Context.None],
    ['[[ x ]] = [undefined];', Context.None],
    ['[[ x ]] = [null];', Context.None],
    ['[...[a] = 1]', Context.None],
    ['[...[ x = 5 ] ] = x', Context.None],
    ['function foo([x] = [1]) {}', Context.None],
    ['function foo([x = 1] = [2]) {}', Context.None],
    ['[.../x/]', Context.None],
    ['[.../x/+y]', Context.None],
    ['[.../x//y]', Context.None],
    ['[.../x/g/y]', Context.None],
    ['function foo([{y1:y1 = 1} = {y1:2}] = [{y1:3}]) {}', Context.None],
    ['[...[...[...a]]] = [[[]]];', Context.None],
    ['x; [{ x = 10 } = {}]', Context.None],
    ['[...[a].b1] = 3', Context.None],
    ['[ { x : foo().y } ] = x', Context.None],
    ['[ { x : foo()[y] } ] = x', Context.None],
    ['[ { x : x.y } ] = x', Context.None],
    ['[ [ x ] ] = x', Context.None],
    ['[ [ foo().x ] ] = x', Context.None],
    ['[ [ foo()[x] ] ] = x', Context.None],
    ['[ [ x.y ] ] = x', Context.None],
    ['[ [ x[y] ] ] = x', Context.None],
    ['[ x = 10 ] = x', Context.None],
    ['[ foo().x = 10 ] = x', Context.None],
    ['[ foo()[x] = 10 ] = x', Context.None],
    ['[ x.y = 10 ] = x', Context.None],
    ['[ x[y] = 10 ] = x', Context.None],
    ['[ { x = 10 } = {} ] = x', Context.None],
    ['[ { x : y = 10 } = {} ] = x', Context.None],
    ['[ { x : foo().y = 10 } = {} ] = x', Context.None],
    ['[ { x : foo()[y] = 10 } = {} ] = x', Context.None],
    ['[ [ x = 10 ] = {} ] = x', Context.None],
    ['[[y] = /a/ ]', Context.None],
    ['[{y} = /a/ ]', Context.None],
    ['[ [ foo()[x] = 10 ] = {} ] = x', Context.None],
    ['[ [ x.y = 10 ] = {} ] = x', Context.None],
    ['[x,y,z] = x', Context.None],
    ['[x, y = 42, z] = x', Context.None],
    ['[{x:x = 1, y:y = 2}, [z = 3, z = 4, z = 5]] = x', Context.None],
    ['[(x)] = x', Context.None],
    ['[((x, y) => z).x] = x', Context.None],
    ['[((x, y) => z)["x"]] = x', Context.None],
    ['[ ...(a) ] = x', Context.None],
    ['[ ...(foo.bar) ] = x', Context.None],
    ['[ (foo.bar) ] = x', Context.None],
    ['[ (foo["bar"]) ] = x', Context.None],
    ['[[].length] = x', Context.None],
    ['[[x].length] = x', Context.None],
    ['[{}.length] = x', Context.None],
    ['[{x: y}.length] = x', Context.None],
    ['[...true]', Context.None],
    ['[..."f".toString()]', Context.None],
    ['[...50]', Context.None],
    ['[..."foo"]', Context.None],
    ['[..."foo".bar]', Context.None],
    ['[...(x)]', Context.None],
    ['[...(x,y)]', Context.None],
    ['[..."x".y]', Context.None],
    ['(x|y)^y', Context.None],
    ['[...{a = b}] = x', Context.None],
    ['[..."x" + y]', Context.None],
    ['[[ x ]] = [];', Context.None],
    ['[]', Context.None],
    ['[1,2,3,4,5]', Context.None],
    ['[,]', Context.None],
    ['[,a,]', Context.None],
    ['[a,,,,,,,,,b]', Context.None],
    ['[[[[z++]]]]', Context.None],
    ['array[1] === 2', Context.None],
    ['[1, 2, 3, ...[]]', Context.None],
    ['[1, 2, ...target = source]', Context.None],
    ['[5, ...[6, 7, 8], 9]', Context.None],
    ['[x]', Context.None],
    ['[() => {}]', Context.None],
    ['[abc => {}]', Context.None],
    ['[,,]', Context.None],
    ['[x,,,]', Context.None],
    ['[x,,y]', Context.None],
    ['[this];', Context.None],
    ['[,,,]', Context.None],
    ['[,,x]', Context.None],
    ['[this];', Context.None],
    ['[x, y, ...z]', Context.None],
    ['[x.y] = z', Context.None],
    ['[x().y] = z', Context.None],
    ['[a[x.y]] = z', Context.None],
    ['[x()[y]] = z', Context.None],
    ['[x.y = a] = z', Context.None],
    ['[x().y = a] = z', Context.None],
    ['[a[x.y] = a] = z', Context.None],
    ['[x()[y] = a ] = z', Context.None],
    ['[x.y = a + b] = z', Context.None],
    ['[x().y = a + b] = z', Context.None],
    ['[a[x.y] = a + b] = z', Context.None],
    ['[x()[y] = a + b] = z', Context.None],
    ['[function(){}.length] = x', Context.None],
    ['[5..length] = x', Context.None],
    ['["X".length] = x', Context.None],
    ['[{}.x] = y', Context.None],
    ['[{}[x]] = y', Context.None],
    ['[x, y, ...z]', Context.None],
    [' [...target = source]', Context.None],
    ['[x, ...y, z]', Context.None],
    ['[x, y, ...z = arr]', Context.None],
    ['[x, y, ...z()]', Context.None],
    ['[x, y, ...z + arr]', Context.None],
    ['[x, ...z = arr, y]', Context.None],
    ['[x, ...z(), y]', Context.None],
    ['[x, ...z + arr, y]', Context.None],
    ['[foo = A] = arr;', Context.None],
    ['[foo, bar] = arr;', Context.None],
    ['[foo = A, bar = B] = arr;', Context.None],
    ['[foo, [x,y,z], bar = B] = arr;', Context.None],
    ['[foo, [[[[[[[[[[[[[x,y,z]]]]]]]]]]]]], bar = B] = arr;', Context.None],
    ['[foo, [x,y = 20,z], bar = B] = arr;', Context.None],
    ['foo([a, b] = arr);', Context.None],
    ['[...x.list];', Context.None],
    ['[...x.list] = a;', Context.None],
    ['[...x = y];', Context.None],
    ['[...x += y];', Context.OptionsRanges],
    ['[...[x].map(y, z)];', Context.OptionsRanges],
    ['[...[x].map(y, z)[x]] = a;', Context.OptionsRanges],
    ['x, [foo, bar] = doo', Context.OptionsRanges],
    ['x, [foo = y, bar] = doo', Context.OptionsRanges],
    ['x = [a, b] = y', Context.OptionsRanges],
    ['[a, b] = c = d', Context.OptionsRanges],
    ['[[foo].length] = x', Context.OptionsRanges],
    ['[x, y]', Context.OptionsRanges],
    ['[x = y]', Context.OptionsRanges],
    ['[x.y]', Context.OptionsRanges],
    ['[]', Context.None],
    ['[,]', Context.None],
    ['[,,]', Context.None],
    ['[x,]', Context.None],
    ['[x,,,]', Context.OptionsRanges],
    ['[x,,y]', Context.None],
    ['[foo = A] = arr;', Context.OptionsRanges],
    ['[foo, bar] = arr;', Context.OptionsRanges],
    ['[foo = A, bar = B] = arr;', Context.OptionsRanges],
    ['[x &= 42]', Context.OptionsRanges | Context.OptionsRaw],
    ['[a = 2]', Context.None],
    ['[await = x] = x', Context.OptionsRanges],
    ['[await = x]', Context.None],
    ['["x".foo]=x', Context.OptionsRanges | Context.OptionsRaw],
    ['[x.y = z]', Context.OptionsRanges],
    ['[a,b=[x,y]] = z', Context.OptionsRanges],
    ['(foo, [bar, baz] = doo);', Context.None],
    ['[a, {b:d}, c] = obj', Context.OptionsRanges],
    ['[a, {[b]:d}, c] = obj', Context.OptionsRanges],
    ['[please, {[make]: it}, stop] = bwahahahaha', Context.OptionsRanges],
    ['[pweeze = [pretty] = please, {[make]: it}, stop] = bwahahahaha', Context.OptionsRanges],
    ['log({foo: [bar]});', Context.OptionsRanges],
    ['log({foo: [bar]} = obj);', Context.OptionsRanges],
    ['[...{a = b} = c];', Context.OptionsRanges],
    ['[a, {b}, c] = obj', Context.OptionsRanges],
    ['[z++]', Context.OptionsRanges],
  ]);
});
