import { Context } from '../../../src/common';
import * as t from 'assert';
import { parseSource } from '../../../src/parser';
import { fail } from '../../test-utils';

describe('Miscellaneous - Escaped keywords', () => {
  for (const arg of [
    '(\\u0069mplements = 1);',
    'var impl\\u0065ments = 1;',
    'var { impl\\u0065ments  } = {};',
    '(\\u0069nterface = 1);',
    'var int\\u0065rface = 1;',
    'var { int\\u0065rface  } = {};',
    '(p\\u0061ckage = 1);',
    'var packa\\u0067e = 1;',
    'var { packa\\u0067e  } = {};',
    '(p\\u0072ivate = 1);',
    'var p\\u0072ivate;',
    'var { p\\u0072ivate } = {};',
    '(prot\\u0065cted);',
    'var prot\\u0065cted = 1;',
    'var { prot\\u0065cted  } = {};',
    '(publ\\u0069c);',
    'var publ\\u0069c = 1;',
    'var { publ\\u0069c } = {};',
    '(st\\u0061tic);',
    'var st\\u0061tic = 1;',
    'var { st\\u0061tic } = {};',
    'l\\u0065t\na',
    'if (true) l\\u0065t: ;',
    'function l\\u0065t() { }',
    '(function l\\u0065t() { })',
    'async function l\\u0065t() { }',
    '(async function l\\u0065t() { })',
    //'(async ()=>{\\u0061wait 100})()',
    //'(async ()=>{var \\u0061wait = 100})()',
    'l\\u0065t => 42',
    // '(\\u0061sync ())',
    'async l\\u0065t => 42',
    'function packag\\u0065() {}',
    'function impl\\u0065ments() {}',
    'function privat\\u0065() {}',
    '(y\\u0069eld);',
    'var y\\u0069eld = 1;',
    'var { y\\u0069eld } = {};'
  ]) {
    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`${arg}`, undefined, Context.None);
      });
    });
  }

  fail('Miscellaneous - Escaped identifiers (failures)', [
    ['import* \\u0061s foo from "./icefapper.js";', Context.Strict | Context.Module],
    ['void \\u0061sync function* f(){};', Context.Strict | Context.Module],
    ['a(1,2\\u0063onst foo = 1;', Context.None],
    ['class C { static async method() { void \\u0061wait; }}', Context.None],
    ['\\u0063o { } while(0)', Context.None],
    ['cl\\u0061ss Foo {}', Context.None],
    ['v\\u0061r', Context.None],
    ['({\\u0067et get(){}})', Context.None],
    ['({\\u0073et set(){}})', Context.None],
    // ['le\\u0074 x = 5', Context.None],
    ['var v\\u0061r = 2000000;', Context.None],
    ['var v\\u{0061}r = 2000000', Context.None],
    // ['String.raw`var {v\\u0061r} = obj`', Context.None],
    ['var {var:v\\u0061r} = obj', Context.None],
    ['[v\\u{0061}r] = obj', Context.None],
    ['function a({var:v\\u{0061}r}) { }', Context.None],
    ['(function v\\u0061r() { })', Context.None],
    ['(function a(v\\u0061r) { })', Context.None],
    ['(function a({v\\u{0061}r}) { })', Context.None],
    ['(function a([{v\\u{0061}r}]) { })', Context.None],
    ['(function a([[v\\u{0061}r]]) { })', Context.None],
    ['(function a({ hello: [v\\u{0061}r]}) { })', Context.None],
    ['(function a({ 0: {var:v\\u{0061}r}}) { })', Context.None],
    ['try { } catch(v\\u{0061}r) { }', Context.None],
    ['var obj = { async method() { void \\u0061wait; } };', Context.Strict],
    ['class C { async *gen() { void \\u0061wait; }}', Context.None],
    ['async() => { void \\u0061wait; };', Context.None],
    ['{for(o i\\u006E {}){}}', Context.None],
    ['class X { se\\u0074 x(value) {} }', Context.None],
    ['class X { st\\u0061tic y() {} }', Context.None],
    //['(function* () { y\\u0069eld 10 })', Context.None],
    ['({ \\u0061sync x() { await x } })', Context.None],
    ['export \\u0061sync function y() { await x }', Context.Module],

    ['{for(o i\\u006E {}){}}', Context.None],
    ['{for(o i\\u006E {}){}}', Context.None],
    ['{for(o i\\u006E {}){}}', Context.None],
    ['{for(o i\\u006E {}){}}', Context.None],
    //    ['impleme\\u{006E}ts', Context.Strict],
    //    ['impleme\\u{006E}ts', Context.Strict | Context.Module],
    //  [`'use strict'; impleme\\u{006E}ts`, Context.None],
    ['[th\\u{69}s] = []', Context.None],
    ['th\\u{69}s', Context.None],
    ['[f\\u0061lse] = []', Context.None],
    ['f\\u0061lse', Context.None],
    ['class C { static async method() { void \u0061wait; }}', Context.None],
    ['while (i < 10) { if (i++ & 1) c\\u006fntinue; this.x++; }', Context.None],
    ['(function a({ hello: {var:v\\u{0061}r}}) { })', Context.None],
    ['[v\\u{0061}r] = obj', Context.None],
    ['t\\u0072y { true } catch (e) {}', Context.None],
    ['var x = typ\\u0065of "blah"', Context.None],
    ['v\\u0061r a = true', Context.None],
    ['thi\\u0073 = 123;', Context.None],
    ['i\\u0066 (false) {}', Context.None],
    ['for (var i = 0; i < 100; ++i) { br\\u0065ak; }', Context.None],
    ['cl\\u0061ss Foo {}', Context.None],
    ['var f = f\\u0075nction() {}', Context.None],
    ["thr\\u006fw 'boo';", Context.None],
    ['w\\u0069th (this.scope) { }', Context.None],
    ['n\\u0075ll = 1;', Context.None],
    ['(x === tr\\u0075e);', Context.None],
    ['do { ; } wh\\u0069le (true) { }', Context.None],
    ['class X { st\\u0061tic y() {} }', Context.None],
    ['class C { st\\u0061tic set bar() {} }', Context.None],
    ['class C { st\\u0061tic *bar() {} }', Context.None],
    ['let l\\u0065t = 1', Context.None],
    ['const l\\u0065t = 1', Context.None],
    ['let [l\\u0065t] = 1', Context.None],
    ['const [l\\u0065t] = 1', Context.None],
    ['for (let l\\u0065t in {}) {}', Context.None],
    ['if ("foo" \\u0069n this) {}', Context.None],
    ['if (this \\u0069nstanceof Array) {}', Context.None],
    ['(n\\u0065w function f() {})', Context.None],
    ['(typ\\u0065of 123)', Context.None],
    ['(v\\u006fid 0)', Context.None],
    ['var \\u{65}\\u{6e}\\u{75}\\u{6d} = 123;', Context.None],
    ['do { ; } wh\\u0069le (true) { }', Context.None],
    //['(function*() { return (n++, y\\u0069eld 1); })()', Context.None],
    ['var \\u0064elete = 123;', Context.None],
    ['var \\u{62}\\u{72}\\u{65}\\u{61}\\u{6b} = 123;', Context.None],
    ['var \\u0062\\u0072\\u0065\\u0061\\u006b = 123;;', Context.None],
    ['var \\u{63}ase = 123;', Context.None],
    ['var \\u{63}atch = 123;', Context.None],
    ['var \\u{63}ontinue = 123;', Context.None],
    ['var fina\\u{6c}ly = 123;', Context.None],
    ['var \\u{64}\\u{6f} = 123;', Context.None],
    ['i\\u0066 (0)', Context.None],
    ['var i\\u0066', Context.None],
    ['export {a \\u0061s b} from "";', Context.Strict | Context.Module],
    ['export {} fr\\u006fm "";', Context.Strict | Context.Module],
    ['for (a o\\u0066 b);', Context.None],
    ['class a { st\\u0061tic m(){} }', Context.None],
    ['var \\u{64}\\u{6f} = 123;', Context.None],
    ['(async function() { aw\\u0061it x })', Context.None],
    ['(\\u0061sync function() { await x })', Context.None],
    ['(\\u0061sync () => { await x })', Context.None],
    ['\\u0061sync x => { await x }', Context.None],
    ['class X { \\u0061sync x() { await x } }', Context.None],
    ['class X { static \\u0061sync x() { await x } }', Context.None],
    ['export \\u0061sync function y() { await x }', Context.Strict | Context.Module],
    ['export default \\u0061sync function () { await x }', Context.Strict | Context.Module],
    ['({ \\u0061sync x() { await x } })', Context.None],
    ['for (x \\u006ff y) {}', Context.None],
    ['(async function() { aw\\u0061it x })', Context.None],
    ['(function*() { var y\\u0069eld = 1; })()', Context.None],
    //['(function*() { y\\u0069eld 1; })()', Context.None],
    ['w\\u0069th (this.scope) { }', Context.None],
    ['wh\\u0069le (true) { }', Context.None],
    ['n\\u0065w function f() {}', Context.None],
    ['async () => { aw\\u{61}it: x }', Context.None],
    ['f\\u006fr (var i = 0; i < 10; ++i);', Context.None],
    ['try { } catch (e) {} f\\u0069nally { }', Context.None],
    ['d\\u0065bugger;', Context.None],
    ['if (d\\u006f { true }) {}', Context.None],
    ['\\u{74}rue', Context.None],
    ['var \\u{64}\\u{6f} = 123;', Context.None],
    ['var \\u{64}\\u{6f} = 123;', Context.Strict | Context.Module],
    ['function impl\\u0065ments() {}', Context.Strict],
    ['function impl\\u0065ments() {}', Context.Strict | Context.Module]
  ]);
});
