import * as t from 'node:assert/strict';
import { outdent } from 'outdent';
import { describe, it } from 'vitest';
import { parseSource } from '../../../src/parser';
import { fail, pass } from '../../test-utils';

describe('Statements - For in', () => {
  for (const arg of [
    'for (x+b in y);',
    'for (b++ in y);',
    'for ([...x,] in [[]]);',
    'for (x = 0 in {});',
    'for(o[0] = 0 in {});',
    'for ((a++) in c);',
    'for (+a().b in c);',
    'for (void a.b in c);',
    'for (/foo/ in {});',
    'for ("foo".x = z in y);',
    'for ("foo" in y);',
    'for ([...[a]] = 0 in   {});',
    'for ([] = 0 in {});',
    'for ([...[a]] = 0 in {});',
    'for ({x} = 0 in {});',
    'for ({p: x = 0} = 0 in {});',
    'for ([] = 0 of {});',
    'for ({x} = 0 of {});',
    'for([0] in 0);',
    'for({a: 0} in 0);',
    'for ({}.x);',
    'for(const let in 0);',
    'for(let let of 0);',
    'for((0) of 0);',
    'for((0) in 0);',
    'for(([0]) in 0);',
    'for(({a: 0}) in 0);',
    'for(0 in 0);',
  ]) {
    it(`${arg}`, () => {
      t.throws(() => {
        parseSource(`${arg}`, { webcompat: true });
      });
    });

    it(`${arg}`, () => {
      t.throws(() => {
        parseSource(`${arg}`, { webcompat: true, lexical: true });
      });
    });
  }
  // ForInOfLoopInitializer only applies in strict mode when webCompat is off
  for (const arg of [
    'for(var x=1 in [1,2,3]) 0',
    'for (var x = 1 in y) {}',
    'for (var a = 0 in {});',
    'for (var a = ++b in c);',
    'for (var a = b in c);',
    'for (var a = 0 in stored = a, {});',
    'for (var a = (++effects, -1) in x);',
  ]) {
    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`${arg}`, { webcompat: true });
      });
    });

    it(`${arg}`, () => {
      t.throws(() => {
        parseSource(`${arg}`, { webcompat: true, impliedStrict: true });
      });
    });

    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`${arg}`);
      });
    });

    it(`${arg}`, () => {
      t.throws(() => {
        parseSource(`${arg}`, { impliedStrict: true });
      });
    });
  }

  for (const arg of [
    '"use strict";\nfor (var a = 0 in {});',
    'for(var [] = 0 in {});',
    'for(var [,] = 0 in {});',
    'for(var [a] = 0 in {});',
    'for (([x])=y in z);',
    'for (a = 0 in {});',
    'for ([...x,] in [[]]) ;',
    'for(var [a = 0] = 0 in {});',
    'for(var [...a] = 0 in {});',
    'for(var [...[]] = 0 in {});',
    'for(var [...[a]] = 0 in {});',
    'for(var {} = 0 in {});',
    'for(var {p: x} = 0 in {});',
    'for(var {p: x = 0} = 0 in {});',
    'for(var {x} = 0 in {});',
    'for(var {x = 0} = 0 in {});',
    'for(let x = 0 in {});',
    'for(let [] = 0 in {});',
    'for(let [,] = 0 in {});',
    'for(let [a] = 0 in {});',
    'for(let [a = 0] = 0 in {});',
    'for(let [...a] = 0 in {});',
    'for(let [...[]] = 0 in {});',
    'for(let [...[a]] = 0 in {});',
    'for(let {} = 0 in {});',
    'for(let {p: x} = 0 in {});',
    'for(let {p: x = 0} = 0 in {});',
    'for(let {x} = 0 in {});',
    'for(let {x = 0} = 0 in {});',
    'for(const x = 0 in {});',
    'for(const [] = 0 in {});',
    'for(const [,] = 0 in {});',
    'for(const [a] = 0 in {});',
    'for(const [a = 0] = 0 in {});',
    'for(const [...a] = 0 in {});',
    'for(const [...[]] = 0 in {});',
    'for(const [...[a]] = 0 in {});',
    'for(const {} = 0 in {});',
    'for(const {p: x} = 0 in {});',
    'for(const {p: x = 0} = 0 in {});',
    'for(const {x} = 0 in {});',
    'for(const {x = 0} = 0 in {});',
    'for ([...x,] in [[]]);',
    'for ((x in b) in u) {};',
    'for (3in {});',
    'for (x = 5 in y) ;',
    'for (a?b:(c in y) in d)z;',
    'for (a,b in c);',
    'for (var a,b in c);',
    'for (var a=1,b in c);',
    'for (x+b++ in y);',
    'for (key instanceof bar in foo);',
    'for (a && b in c);',
    'for (~a[b] in c);',
    'for ((x=5)in y);',
    'for (x+b in y);',
    'for (b++ in y);',
    'for ((a,b) in c);',
    'for (((a,b)) in c);',
    'for (((a),b) in c);',
    'for ((a?b:c) in y)z;',
    'for (~a().b in c);',
    'for (~a()[b] in c);',
    'for (++a().b in c);',
    'for (++a()[b] in c);',
    'for (+a in c);',
    'for (+a.b in c);',
    'for (+a[b] in c);',
    'for (+a().b in c);',
    'for (+a()[b] in c);',
    'for (--a in c);',
    'for (--a.b in c);',
    'for (--a[b] in c);',
    'for (--a().b in c);',
    'for (--a()[b] in c);',
    'for (void a in c);',
    'for (void a.b in c);',
    'for (void a[b] in c);',
    'for ((a++) in c);',
    'for ((++a) in c);',
    'for ((--a) in c);',
    'for ((a--) in c);',
    'for ((x=a?b:c) in y)z;',
    'for ((x = [x in y]) in z);',
    'for ((x = {x:x in y}) in z);',
    'for (new a.b in c);',
    'for (5 in {});',
    "for ('x' in {});",
    'for (true in {});',
    'for (false in {});',
    'for (null in {});',
    'for (/foo/ in {});',
    'for (x = 0 in {});',
    'for(o[0] = 0 in {});',
    'for ((a++) in c);',
    'for (void a.b in c);',
    'for (/foo/ in {});',
    'for([...[]] = 0 in {});',
    'for([...[a]] = 0 in {});',
    'for({} = 0 in {});',
    'for({p: x} = 0 in {});',
    'for({p: x = 0} = 0 in {});',
    'for({x} = 0 in {});',
    'for({x = 0} = 0 in {});',
    'for(o.p = 0 in {});',
    'for(o[0] = 0 in {});',
    'for(f() = 0 in {});',
    'for(let a = 0 in b);',
    'for(const a = 0 in b);',
    'for(({a}) in 0);',
    'for(([a]) in 0);',
    'for(var [] = 0 in b);',
    'for(var {} = 0 in b);',
    'for(let a = 0 in b);',
    'for(const a = 0 in b);',
    '"use strict"; for(var a = 0 in b);',
    'for ("foo".x = y in y) {}',
    'for ({}.x = y in y) {}',
    'for ("foo".x in y',
    'for ([].x = y in y) {}',
    'for (a() in b) break',
  ]) {
    it(`${arg}`, () => {
      t.throws(() => {
        parseSource(`${arg}`);
      });
    });
  }

  for (const arg of [
    'for (var a = b, c, d, b = a ; x in b ; ) { break }',
    'for ([].x in y) {}',
    'for (var {j} in x) { foo = j }',
    'for (var {j} in x) { [foo] = [j] }',
    'for (var {j} in x) { [[foo]=[42]] = [] }',
    'for (var {j} in x) { var foo = j }',
    'for (var {j} in x) { var [foo] = [j] }',
    'for (var {j} in x) { var [[foo]=[42]] = [] }',
    'for (var {j} in x) { var foo; foo = j }',
    'for ("foo".x in y) {}',
    'for ("foo".x in y) {}',
    'for ({}.x in y) {}',
    'for (a[b in c] in d);',
    'for (var {j} in x) { var foo; [foo] = [j] }',
    'for (var {j} in x) { var foo; [[foo]=[42]] = [] }',
    'for (var {j} in x) { let foo; foo = j }',
    'for (var {j} in x) { let foo; [foo] = [j] }',
    'for (var {j} in x) { let foo; [[foo]=[42]] = [] }',
    'for (var {j} in x) { let foo = j }',
    'for (var {j} in x) { let [foo] = [j] }',
    'for (var {j} in x) { const foo = j }',
    'for (var {j} in x) { const [foo] = [j] }',
    'for (var {j} in x) { function foo() {return j} }',
    'for (let j in x) { foo = j }',
    'for (let j in x) { [foo] = [j] }',
    'for (let j in x) { [[foo]=[42]] = [] }',
    'for (let j in x) { var foo = j }',
    'for (let j in x) { var [foo] = [j] }',
    'for (let j in x) { var [[foo]=[42]] = [] }',
    'for (let j in x) { var foo; foo = j }',
    'for (let j in x) { var foo; [foo] = [j] }',
    'for (let j in x) { var foo; [[foo]=[42]] = [] }',
    'for (let j in x) { let foo; foo = j }',
    'for (let j in x) { let foo; [foo] = [j] }',
    'for (let j in x) { let foo; [[foo]=[42]] = [] }',
    'for (let j in x) { let foo = j }',
    'for (let j in x) { let [foo] = [j] }',
    'for (let j in x) { const foo = j }',
    'for (let j in x) { const [foo] = [j] }',
    'for (let j in x) { function foo() {return j} }',
    'for (let {j} in x) { foo = j }',
    'for (let {j} in x) { [foo] = [j] }',
    'for (let {j} in x) { [[foo]=[42]] = [] }',
    'for (let {j} in x) { var foo = j }',
    'for (let {j} in x) { var [foo] = [j] }',
    'for (let {j} in x) { var [[foo]=[42]] = [] }',
    'for (let {j} in x) { var foo; foo = j }',
    'for (let {j} in x) { var foo; [foo] = [j] }',
    'for (let {j} in x) { var foo; [[foo]=[42]] = [] }',
    'for (let {j} in x) { let foo; foo = j }',
    'for (let {j} in x) { let foo; [foo] = [j] }',
    'for (let {j} in x) { let foo; [[foo]=[42]] = [] }',
    'for (let {j} in x) { let foo = j }',
    'for (let {j} in x) { let [foo] = [j] }',
    'for (let {j} in x) { const foo = j }',
    'for (let {j} in x) { const [foo] = [j] }',
    'for (let {j} in x) { function foo() {return j} }',
    'for (const j in x) { foo = j }',
    'for (const j in x) { [foo] = [j] }',
    'for (const j in x) { [[foo]=[42]] = [] }',
    'for (const j in x) { var foo = j }',
    'for (const j in x) { var [foo] = [j] }',
    'for (const j in x) { var [[foo]=[42]] = [] }',
    'for (const j in x) { var foo; foo = j }',
    'for (const j in x) { var foo; [foo] = [j] }',
    'for (const j in x) { var foo; [[foo]=[42]] = [] }',
    'for (const j in x) { let foo; foo = j }',
    'for (const j in x) { let foo; [foo] = [j] }',
    'for (const j in x) { let foo; [[foo]=[42]] = [] }',
    'for (const j in x) { let foo = j }',
    'for (j in x) { foo = j }',
    'for (j in x) { [foo] = [j] }',
    'for (j in x) { [[foo]=[42]] = [] }',
    'for (j in x) { var foo = j }',
    'for (j in x) { var [foo] = [j] }',
    'for (j in x) { var [[foo]=[42]] = [] }',
    'for (j in x) { var foo; foo = j }',
    'for (j in x) { var foo; [foo] = [j] }',
    'for (j in x) { var foo; [[foo]=[42]] = [] }',
    'for (j in x) { let foo; foo = j }',
    'for (j in x) { let foo; [foo] = [j] }',
    'for (j in x) { let foo; [[foo]=[42]] = [] }',
    'for (j in x) { let foo = j }',
    'for (j in x) { let [foo] = [j] }',
    'for (j in x) { const foo = j }',
    'for (j in x) { const [foo] = [j] }',
    'for (j in x) { function foo() {return j} }',
    'for ({j} in x) { foo = j }',
    'for ({j} in x) { [foo] = [j] }',
    'for ({j} in x) { [[foo]=[42]] = [] }',
    'for ({j} in x) { var foo = j }',
    'for ({j} in x) { var [foo] = [j] }',
    'for ({j} in x) { var [[foo]=[42]] = [] }',
    'for ({j} in x) { var foo; foo = j }',
    'for ({j} in x) { var foo; [foo] = [j] }',
    'for ({j} in x) { var foo; [[foo]=[42]] = [] }',
    'for ({j} in x) { let foo; foo = j }',
    'for ({j} in x) { let foo; [foo] = [j] }',
    'for ({j} in x) { let foo; [[foo]=[42]] = [] }',
    'for ({j} in x) { let foo = j }',
    'for ({j} in x) { let [foo] = [j] }',
    'for ({j} in x) { const foo = j }',
    'for ({j} in x) { const [foo] = [j] }',
    'for ({j} in x) { function foo() {return j} }',
    'for (var j in x) { foo = j }',
    'for (var j in x) { [foo] = [j] }',
    'for (var j in x) { [[foo]=[42]] = [] }',
    'for (var j in x) { var foo = j }',
    'for (var j in x) { var [foo] = [j] }',
    'for (var j in x) { var [[foo]=[42]] = [] }',
    'for (var j in x) { var foo; foo = j }',
    'for (var j in x) { var foo; [foo] = [j] }',
    'for (var j in x) { var foo; [[foo]=[42]] = [] }',
    'for (var j in x) { let foo; foo = j }',
    'for (var j in x) { let foo; [foo] = [j] }',
    'for (var j in x) { let foo; [[foo]=[42]] = [] }',
    'for (var j in x) { let foo = j }',
    'for (var j in x) { let [foo] = [j] }',
    'for (var j in x) { const foo = j }',
    'for (var j in x) { const [foo] = [j] }',
    'for (var j in x) { function foo() {return j} }',
    'for (var {j} in x) { foo = j }',
    'for (let in {}) {}',
    'for (var let = 1; let < 1; let++) {}',
    'for (var let in {}) {}',
    'for (var [let] = 1; let < 1; let++) {}',
    'for (var [let] in {}) {}',
    'for (var {j} in x) { [foo] = [j] }',
    'for (var {j} in x) { [[foo]=[42]] = [] }',
    'for (var {j} in x) { var foo = j }',
    'for (var {j} in x) { var [foo] = [j] }',
    'for(var a in b);',
    'for(a in b);',
    'for(let of in of);',
    'for(const a in b);',
    'for (var {j} in x) { var [[foo]=[42]] = [] }',
    'for (var {j} in x) { var foo; foo = j }',
    'for (var {j} in x) { var foo; [foo] = [j] }',
    'for (var {j} in x) { var foo; [[foo]=[42]] = [] }',
    'for (var {j} in x) { let foo; foo = j }',
    'for (var {j} in x) { let foo; [foo] = [j] }',
    'for (var {j} in x) { let foo; [[foo]=[42]] = [] }',
    'for (var {j} in x) { let foo = j }',
    'for (var {j} in x) { let [foo] = [j] }',
    'for (var {j} in x) { const foo = j }',
    'for (var {j} in x) { const [foo] = [j] }',
    'for (var {j} in x) { function foo() {return j} }',
    'for (let j in x) { foo = j }',
    'for (let j in x) { [foo] = [j] }',
    'for (let j in x) { [[foo]=[42]] = [] }',
    'for (const j in x) { let [foo] = [j] }',
    'for (const j in x) { const foo = j }',
    'for (const j in x) { const [foo] = [j] }',
    'for (const j in x) { function foo() {return j} }',
    'for (const {j} in x) { foo = j }',
    'for (const {j} in x) { [foo] = [j] }',
    'for (const {j} in x) { [[foo]=[42]] = [] }',
    'for (const {j} in x) { var foo = j }',
    'for (const {j} in x) { var [foo] = [j] }',
    'for (const {j} in x) { var [[foo]=[42]] = [] }',
    'for (const {j} in x) { var foo; foo = j }',
    'for (const {j} in x) { var foo; [foo] = [j] }',
    'for (const {j} in x) { var foo; [[foo]=[42]] = [] }',
    'for (const {j} in x) { let foo; foo = j }',
    'for (const {j} in x) { let foo; [foo] = [j] }',
    'for (const {j} in x) { let foo; [[foo]=[42]] = [] }',
    'for (const {j} in x) { let foo = j }',
    'for (const {j} in x) { let [foo] = [j] }',
    'for (const {j} in x) { const foo = j }',
    'for (const {j} in x) { const [foo] = [j] }',
    'for (const {j} in x) { function foo() {return j} }',
    '2; for (var b in { x: 0 }) { 3; }',
    '2; for (const b in { x: 0 }) { 3; }',
    '2; for (let b in { x: 0 }) { 3; }',
    'for ( [let][1] in obj ) ;',
    'for (x.y in { attr: null }) {}',
    'for ((x) in { attr: null }) {}',
    'for ( let[x] in obj ) {}',
    'for ((a in b).x in {});',
    'for (x in null, { key: 0 }) {}',
    'for ((let.x) of []) {}',
    'for (let a = b => { return b in c; }; ;);',
    'for (let a = (b in c); ;);',
    'for (let a = (b in c && d); ;);',
    'for (let a = b => (b in c); ;);',
    'for (let a = ((b in c) && (d in e)); ;);',
    'for (let a = (b && c in d); ;);',
    'for (let a = (b => c => b in c); ;);',
    'for (/foo/g[x] in c) d;',
    'for (/foo/g.x in c) d;',
    'for (456[x] in c) d;',
    'for (456..x in c) d;',
    'for (/foo/[x] in c) d;',
    'for (/foo/.x in c) d;',
    'for ("foo"[x] in c) d;',
    'for ("foo".x in c) d;',
    'for (true.x in c) d;',
    'for ([][y] <<= p;;) x;',
    'for ([].w ^= s;;) x;',
    'for(function(){};;)x',
    'for(function(){if(x in 3);};;)x',
    'for ([].w ^= s;;) x;',
    'for ([][y] <<= p;;) x;',
    'for ([].u |= c;;) x;',
    'for ({}[y] ^= x;;) x;',
    'for ({}.u |= c;;) x;',
    'for ({}[y] ^= x;;) x;',
    'for (function(){ }[foo] in x);',
    'for (function(){ }[x in y] in x);',
    'for (function(){ if (a in b); }.prop in x);',
    'for (function(){ a in b; }.prop in x);',
    'for(function(){do;while(x in t)};;)x',
    'for(function(){while(x in y)t};;)x',
    'for (function(){};;);',
    'for (function(){ }[foo];;);',
    'for (function(){ }[x in y];;);',
    'for (function(){ if (a in b); };;);',
    'for (function(){ a in b; };;);',
    'for (function(){ a in b; }.foo;;);',
  ]) {
    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`${arg}`);
      });
    });

    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`${arg}`);
      });
    });

    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`${arg}`);
      });
    });

    it(`${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`${arg}`, { lexical: true });
      });
    });

    it(`async(); ${arg}`, () => {
      t.doesNotThrow(() => {
        parseSource(`async(); ${arg}`);
      });
    });

    it(`function foo() { ${arg} }`, () => {
      t.doesNotThrow(() => {
        parseSource(`function foo() { ${arg} }`);
      });
    });
  }

  fail('Statements - For in (fail)', [
    'for (var x in {}) function* g() {}',
    'for ([(x, y)] in {}) {}',
    'for ({ m() {} } in {}) {}',
    'for (var x in {}) label1: label2: function f() {}',
    'for (x in {}) label1: label2: function f() {}',
    'for (let x in {}) label1: label2: function f() {}',
    'for (let x in {}) label1: label2: function f() {}',
    'for ([...x = 1] in [[]]) ;',
    'for ({ yield } in [{}]) ; });',
    'for ([...{ get x() {} }] in [[[]]]) ;',
    { code: 'for ({ x: [x = yield] } in [{ x: [] }]) ;', options: { impliedStrict: true } },
    { code: 'for ({ x = yield } in [{}]) ;', options: { impliedStrict: true } },
    'for(var {x = 0} = 0 in {});',
    { code: 'for ({ x: { x = yield } } in [{ x: {} }]) ;', options: { impliedStrict: true } },
    'for ({...rest, b} in [{}]) ;',
    'for(let x = 0 in {});',
    'for ([...x,] in [[]]) ;',
    'for (const a = 0 in {});',
    'for (let a = 0 in {});',
    'for ({ m() {} } in {}) {}',
    'for (a=>b in c);',
    'for ("foo" in y);',
    'for ("foo".x = z in y);',
    'for (()=>x in y);',
    'for (()=>(x) in y);',
    'for(([0]) in 0);',
    'for(({a: 0}) in 0);',
    'for ((()=>x) in y);',
    'for (const [x,y,z] = 22 in foo);',
    'for (true ? 0 : 0 in {}; false; ) ;',
    'for (x = 22 in foo);',
    'for ({a:x,b:y,c:z} = 22 in foo);',
    'for ([x,y,z] = 22 in foo);',
    'for (const x = 22 in foo);',
    'for (const {a:x,b:y,c:z} = 22 in foo);',
    'for (0 = 0 in {});',
    'for (i++ = 0 in {});',
    'for (new F() = 0 in {});',
    'for ("foo".x += z in y);',
    'for (function () {} in a)',
    'for ([]);',
    'for (var [a] = 0 in {});',
    'for (var {a} = 0 in {});',
    'for(var [a = 0] = 0 in {});',
    { code: 'for (let in o) { }', options: { impliedStrict: true } },
    'for(var [...a] = 0 in {});',
    'for (var a = () => { return "a"} in {});',
    'for (const ...x in y){}',
    'for (...x in y){}',
    'for (let a = b => b in c; ;);',
    'for(let x = 0 in {});',
    'for(let [] = 0 in {});',
    'for(let [,] = 0 in {});',
    'for (let x = 3 in {}) { }',
    'for (let x = 3, y in {}) { }',
    'for (let x = 3, y = 4 in {}) { }',
    'for (let x, y = 4 in {}) { }',
    'for (let x, y in {}) { }',
    'for(let [a] = 0 in {});',
    'for(const {x = 0} = 0 in {});',
    'for([,] = 0 in {});',
    'for([a] = 0 in {});',
    { code: 'for (let.x in {}) {}', options: { impliedStrict: true } },
    { code: 'for (let in {}) { }', options: { impliedStrict: true } },
    { code: '"use strict"; for (let.x of []) {}', options: { impliedStrict: true } },
    '"use strict"; for (let.x of []) {}',
    'for await (let.x of []) {}',
    'for (let + x in y);',
    'for (let => {} in y);',
    'for (let() in y);',
    'for (let, x in y);',
    { code: 'for await (let.x of []) {}', options: { impliedStrict: true } },
    '"use strict"; for (let.x in {}) {}',
    'for([a] = 0 in {});',
    'for([a = 0] = 0 in {});',
    'for([...a] = 0 in {});',
    'for([...[a]] = 0 in {});',
    'for({} = 0 in {});',
    'for({p: x} = 0 in {});',
    'for({p: x = 0} = 0 in {});',
    'for({x} = 0 in {});',
    'for({x = 0} = 0 in {});',
    'for(f() = 0 in {});',
    'for(let [a = 0] = 0 in {});',
    'for(let [...a] = 0 in {});',
    'for(let [...[]] = 0 in {});',
    'for(let [...[a]] = 0 in {});',
    'for(let {} = 0 in {});',
    'for(let {p: x} = 0 in {});',
    'for(let {p: x = 0} = 0 in {});',
    'for(let {x} = 0 in {});',
    'for(let {x = 0} = 0 in {});',
    'for(const x = 0 in {});',
    'for(const [] = 0 in {});',
    'for(const [,] = 0 in {});',
    'for(const [a] = 0 in {});',
    'for ({ x: [(x, y)] } in [{ x: [] }]) ;',
    'for(let ? b : c in 0);',
    { code: 'for ({ eval } in [{}]) ;', options: { impliedStrict: true } },
    { code: 'for ({ eval } in [{}]) ;', options: { impliedStrict: true, webcompat: true } },
    'for (var i, j = void 0 in [1, 2, 3]) {}',
    'function foo() { for (var i, j of {}) {} }',
    '"use strict"; for ([ x = yield ] in [[]]) ;',
    'for ([[(x, y)]] in [[[]]]) ;',
    '"use strict"; for ([[x[yield]]] in [[[]]]) ;',
    '"use strict"; for ([{ x = yield }] in [[{}]]) ;',
    'for ([...x,] in [[]]) ;',
    'for ([...{ get x() {} }] in [[[]]]) ;',
    'for ([...{ get x() {} }] in [[[]]]) ;',
    '"use strict"; for ({ x = yield } in [{}]) ;',
    'for (let x in {}) label1: label2: function f() {}',
    'for (x in {}) label1: label2: function f() {}',
    'for (var [a] = 0 in {});',
    '"use strict"; for (var i=0 in j);',
    'for (var {x}=0 in y);',
    '"use strict"; for (var {x}=0 in y);',
    'or (var [p]=0 in q);',
    '"use strict"; for (var [p]=1 in q);',
    'for (const x = 0 in {});',
    'for (let x = 0 in {});',
    'for ((a--) in c);',
    'for (this in {}; ;);',
    'for (this in {});',
    'for (x = y in z) ;',
    'for (function(){} in x);',
    'for ((x = y) in z) ;',
    'for ([x + y] in obj);',
    'for ([x] = z in obj);',
    'for ([x.y] = z in obj);',
    'for ([x + y] = z in obj);',
    'for ({a: x + y} in obj);',
    'for ({x} = z in obj);',
    'for ({a: x.y} = z in obj);',
    'for ({a: x + y} = z in obj);',
    'for (let [let] in obj);',
    'for ("foo".bar = x in obj);',
    'for ({}.bar = x in obj);',
    'for ([].bar = x in obj);',
    'for ([]=1 in x);',
  ]);
  pass('Statements - For in (pass)', [
    'for ({x: a.b} in obj);',

    'for ("foo".bar in obj);',
    'for ({}.bar in obj);',
    'for ([].bar in obj);',
    'for (var {x : y} in obj);',
    'for(var x=1 in [1,2,3]) 0',
    'for (var [foo, bar=b] of arr);',
    'for (function* y() { new.target in /(?:()|[]|(?!))/iuy };; (null))  {}',
    'for (var {[x]: y} of obj);',

    'for (var {x = y} in obj);',
    'for (var [] in x);',
    'for (var [foo,] in arr);',
    'for (var a = b in c);',
    { code: 'for (var [foo,bar] in arr);', options: { ranges: true } },
    { code: 'for (let.x in {}) {}', options: { ranges: true } },
    { code: 'for (var [foo,,] in arr);', options: { ranges: true } },
    { code: 'for (var [foo=a, bar=b] in arr);', options: { ranges: true } },
    { code: 'for (var [,] in x);', options: { ranges: true } },
    'for (var [foo] in arr);',
    'for (var [foo=a] in arr);',
    { code: 'for (var [foo=a, bar] in arr);', options: { ranges: true } },
    'for (var [foo, bar=b] in arr);',
    { code: 'for (var [...foo] in obj);', options: { ranges: true } },
    'for (var {} in obj);',
    'for (var {x,} in obj);',
    { code: 'for (var {x, y} in obj);', options: { ranges: true } },
    'for (var {x} in obj);',
    { code: 'for (var {x = y} in obj);', options: { ranges: true } },
    'for (a in b);',
    { code: 'for (a in b); for (a in b); for (a in b);', options: { ranges: true } },
    'for (let a in b);',
    { code: 'for ([a,b] in x) a;', options: { ranges: true } },
    { code: 'for ([a,b] of x) a;', options: { ranges: true } },
    'for ({a,b} in x) a;',
    { code: 'for ({a,b} of x) a;', options: { ranges: true } },
    { code: 'for (const [...x] in y){}', options: { ranges: true } },
    { code: 'for (const {...x} in y){}', options: { ranges: true } },
    { code: 'for (var a=1;;);', options: { ranges: true } },
    'for (var a in b);',
    'for (let a in b);',
    'for (const a in b);',
    'for (a in b=c);',
    'for (var a = ++b in c);',
    'for (var a = 0 in stored = a, {});',
    'for (var a = (++effects, -1) in x);',
    'for (var a in stored = a, {a: 0, b: 1, c: 2});',
    {
      code: 'for (var a = (++effects, -1) in stored = a, {a: 0, b: 1, c: 2});',
      options: { webcompat: true, ranges: true },
    },
    'for ([a.b] in c) d',
    'for ([a.b].foo in c) d',
    'for ({a: b.c} in d) e',
    'for ({a: b.c}.foo in d) e',
    'for(let {a} in []) {}',
    'for(let [a = 1, ...b] in []) {}',
    'for(const {[Symbol.iterator]: a} in []){}',
    'for({a: a} in []){}',
    'for({"a": a} in []){}',
    'for({a=0} in b);',
    'for ({j} in x) { var [foo] = [j] }',
    'for (const {j} in x) { function foo() {return j} }',
    'for (const j in x) { let [foo] = [j] }',
    'for(ind in (hash={2:"b",1:"a",4:"d",3:"c"}))__str+=hash[ind]',
    'for ([arguments] in [[]]) ;',
    'for (let x in null, { key: 0 }) {}',

    'for(let [a=b in c] in null);',
    'for([{a=0}] in b);',
    /*[
      'for(var a = 0 in b, c);',
      Context.None,
      {
        "type": "Program",
        "sourceType": "script",
        "body": [
          {
            "type": "ForInStatement",
            "body": {
              "type": "EmptyStatement"
            },
            "left": {
              "type": "VariableDeclaration",
              "kind": "var",
              "declarations": [
                {
                  "type": "VariableDeclarator",
                  "init": {
                    "type": "Literal",
                    "value": 0
                  },
                  "id": {
                    "type": "Identifier",
                    "name": "a"
                  }
                }
              ]
            },
            "right": {
              "type": "SequenceExpression",
              "expressions": [
                {
                  "type": "Identifier",
                  "name": "b"
                },
                {
                  "type": "Identifier",
                  "name": "c"
                }
              ]
            }
          }
        ]
      }],*/
    'for(var a in b, c);',
    'for ([...{ x = yield }] in [[{}]]) ;',
    'for ( [let][1] in obj ) ;',
    'for ((x) in { attr: null }) {}',
    '2; for (var b in { x: 0 }) { 3; }',
    outdent`
      for (var p in obj) {
          if (obj.hasOwnProperty(p)) {
              if (p === "prop1") {
                  countProp1++;
              }
              if (p === "prop2") {
                  countProp2++;
              }
              if (p === "prop3") {
                  countProp3++;
              }
          }
      }
    `,
    'for(x in list) process(x);',
    'for (var x in list) process(x);',
    'for ([...x] in {ab: a}) {}',
    'for (let {j} in x) { var [foo] = [j] }',
    'for(x of "foo" in {}) {}',
    'for (x in {a: b}) {}',
    'function foo(){ "use strict"; for(x in {}, {}) {} }',
    'for(const x in [1,2,3]) {}',
  ]);
});
